### PR TITLE
Migrate from libsharp2 to ducc0

### PR DESCRIPTION
**Pull request by msyriac**
Thank you Sigurd @amaurea for the awesome effort here.

### CODE REVIEW

**Comment by zatkins2** [comment]
Seconding, big thanks to Sigurd @amaurea. This will be hugely useful (just like `pixell` already!).

I was poking around at this branch and wanted to report a few things in case it's useful.

- Compiling from source was successful both with and without the intel compilers. In both cases tests passed.
- Not sure if tested, but seeing some minor bug in `curvedsky.map2alm`:
```python
>>> # a map with (2, 3) preshape, standard ACT fejer1 footprint, single precision
>>> imap.geometry, imap.dtype
(((2, 3, 10320, 43200),
  car:{cdelt:[-0.008333,0.008333],crval:[0,0],crpix:[21601.00,7560.50]}),
 dtype('<f4'))
>>> # this gives me the 'cyl' case, but I think should be '2d'.
# from the docs, it seems like the '2d' case is when
# an ndmap is fullsky, or can be zero-padded into one as is the case here
>>> curvedsky.analyse_geometry(*imap.geometry).case
'cyl'
>>> # this matters because calling map2alm 
# with method='cyl' or method='auto' results in a
# ValueError relating to broadcasting the (fullsky) quadrature weights against the partial
# sky map (this is probably a minor bug?)
>>> curvedsky.map2alm(imap, lmax=10, method='auto')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[60], line 1
----> 1 curvedsky.map2alm(imap[None, None], lmax=10, method='cyl').shape

File ~/repos/simonsobs/pixell/pixell/curvedsky.py:288, in map2alm(map, alm, lmax, spin, deriv, alm2map_adjoint, copy, method, ainfo, verbose, nthread, niter, epsilon, pix_tol, weights, locinfo)
    286 elif method == "cyl":
    287 	if verbose: print("method: cyl")
--> 288 	return map2alm_cyl(map, alm, ainfo=ainfo, minfo=minfo, lmax=lmax, spin=spin, deriv=deriv, copy=copy,
    289 		verbose=verbose, alm2map_adjoint=alm2map_adjoint, nthread=nthread, niter=niter,
    290 		pix_tol=pix_tol, weights=weights)
    291 elif method == "pos":
    292 	if verbose: print("method: pos")

File ~/repos/simonsobs/pixell/pixell/curvedsky.py:755, in map2alm_cyl(map, alm, ainfo, minfo, lmax, spin, weights, deriv, copy, verbose, alm2map_adjoint, nthread, pix_tol, niter)
    753 	pad  = ((minfo.ypad[0],minfo.xpad[0]),(minfo.ypad[1],minfo.xpad[1]))
    754 	tmap = map2buffer(map[I], minfo.flip, pad)
--> 755 	map2alm_raw_cyl(tmap, alm[I], ainfo=ainfo, lmax=lmax, spin=spin, weights=weights, deriv=deriv, niter=niter, verbose=verbose)
    756 return alm

File ~/repos/simonsobs/pixell/pixell/curvedsky.py:911, in map2alm_raw_cyl(map, alm, ainfo, lmax, spin, weights, deriv, copy, verbose, alm2map_adjoint, niter, nthread)
    909 			def approx_backward(map): return adjoint(wmul(map,weights))
    910 			if alm2map_adjoint: alm_full[Ij] = adjoint(map_full[Ij])
--> 911 			else:               alm_full[Ij] = jacobi_inverse(forward, approx_backward, map_full[Ij], niter=niter)
    912 return alm

File ~/repos/simonsobs/pixell/pixell/curvedsky.py:950, in jacobi_inverse(forward, approx_backward, y, niter)
    939 def jacobi_inverse(forward, approx_backward, y, niter=0):
    940 	"""Given y = forward(x), attempt to recover x using jacobi iteration
    941 	with forward and it's approximate inverse approx_backward. niter
    942 	controls the number of iterations. The number of calls to forward is
   (...)
    948 	is needed, Jacobi might be the best choice.
    949 	"""
--> 950 	x = approx_backward(y)
    951 	for i in range(niter):
    952 		x -= approx_backward(forward(x)-y)

File ~/repos/simonsobs/pixell/pixell/curvedsky.py:909, in map2alm_raw_cyl..approx_backward(map)
--> 909 def approx_backward(map): return adjoint(wmul(map,weights))

File ~/repos/simonsobs/pixell/pixell/curvedsky.py:893, in map2alm_raw_cyl..wmul(map_flat, weights)
    892 def wmul(map_flat, weights):
--> 893 	return (map_flat.reshape(map_flat.shape[:-1]+map.shape[-2:])*weights[:,None]).reshape(map_flat.shape)

ValueError: operands could not be broadcast together with shapes (1,21600,43200) (10320,1) 
>>> # forcing method='2d' works though
>>> curvedsky.map2alm(imap, lmax=10, method='2d').shape
(2, 3, 66)
```
- I haven't tested whether the result in the `2d` case matches old `pixell`/libsharp
- One thing to note about `ducc`, and something that Sigurd has handled with [`get_ducc_maxlmax`](https://github.com/simonsobs/pixell/blob/727fa06f7959944d1318719595c16067e6b18add/pixell/curvedsky.py#L1159), is that it is not permissive with the `lmax` given to a SHT. It prevents you from taking an SHT with a larger `lmax` than these values/beyond which the result is not guaranteed to be exact. `libsharp` did allow this, I guess at the user's risk, but it was often quite useful and safe in real-world settings. The new `lmax` limit is 1 less than the "Nyquist" limit we're used to (e.g. 21599 vs. 21600 for the ACT pixelization).
- Maybe @mreineck can comment -- is there something about the new implementation (i.e., computing exact transforms to much higher `lmax` than before) that makes going beyond the exact `lmax` more dangerous than in `libsharp`, when the exact `lmax` was much lower? At any rate, unclear what the impact of this limitation would be (again, I have found it useful to go beyond the new limit would be, albeit usually by only 1 😛).

Other things to track, but not high priority and probably on Sigurd's (long) list of to-dos!
- A useful function that was in `sharp` but is commented out in `cmisc` now is `transfer_alm`
- Uncommenting `ducc` in `fft.py`

**Comment by mreineck** [comment]
Hi @zatkins2 !

> One thing to note about ducc, and something that Sigurd has handled with [get_ducc_maxlmax](https://github.com/simonsobs/pixell/blob/727fa06f7959944d1318719595c16067e6b18add/pixell/curvedsky.py#L1159), is that it is not permissive with the lmax given to a SHT. It prevents you from taking an SHT with a larger lmax than these values/beyond which the result is not guaranteed to be exact. libsharp did allow this, I guess at the user's risk, but it was often quite useful and safe in real-world settings. The new lmax limit is 1 less than the "Nyquist" limit we're used to (e.g. 21599 vs. 21600 for the ACT pixelization).

As far as I understand it, if you have a grid with a quadrature rule up to (and including) `lmax`, and you try to extract moments higher than `lmax`, you are guaranteed to get meaningless results (they won't be less accurate, but just not helpful at all). I expect that all you will see at these higher moments is aliasing from moments `<=lmax` and no real information about what's "really" happening at the high frequencies, because the chosen grid simply cannot resolve them. The aliasing artifacts won't be as easy to identify as in Cartesian coordinates (there you will clearly see mirroring in Fourier coefficients, which indicates that something is strange), but the situation should be analogous.

Having said this, I think that the transition from "measurable" to "useless" moments is only so sharp for grids where sampling theorems exist (i.e. GL, F1, F2, CC, MW, ...); for grids with only approximate quadrature rules (like Healpix) there is a fairly large grey area.

**Comment by mreineck** [comment]
Concerning `ducc0` installation: I'm not absolutely sure how the `pixell` setup scripts will install the `ducc0` package, but if at all possible, I recommend forcing an installation from *source*, not from binary wheels. The binary wheels are not optimized for the target CPU, and this will probably result in SHTs that are unnecessarily slow (factors of 2 are realistic). Building from source, on the other hand,  will give you a package compiled with `-march=native`.

**Comment by amaurea** [comment]
I've addressed these now.

About it choosing "cyl" instead of "2d": This is because "2d" would require a lot of vertical padding, which would use more memory. I was conflicted on whether to use "2d" in these cases, but I chose to go with the more memory-conservative "cyl", making the user choose "2d" explicitly if they want that.

**Comment by msyriac** [comment]
@mreineck , re: optimized builds, given my past (negative) experience trying to support automated build from source inside the repository on Macs as well as on Github Actions, I am strongly inclined to make things as push button as possible.  My feeling is that beginners using these packages should eat the 2x performance hit from using pre-compiled non-optimized binaries, and "enthusiasts" (including people developing modules for HPC systems) should build each of the components (including ducc0) from source.

**Comment by mreineck** [comment]
Totally understood! I just wanted to clarify that `ducc` has no fancy tricks like multi-target builds and runtime dispatching (yet).  As long as it is clear that "expert installations" require some (minima) manual work (`pip install --no-binary ducc0 ducc0` should be enough), I'm totally happy.

**Comment by zatkins2** [comment]
Not directly related to this PR, but I migrated my lmax question [here](https://github.com/mreineck/ducc/issues/18)!

**Comment by ickc** [comment]
> Concerning `ducc0` installation: I'm not absolutely sure how the `pixell` setup scripts will install the `ducc0` package, but if at all possible, I recommend forcing an installation from _source_, not from binary wheels. The binary wheels are not optimized for the target CPU, and this will probably result in SHTs that are unnecessarily slow (factors of 2 are realistic). Building from source, on the other hand, will give you a package compiled with `-march=native`.

Hi, @mreineck, just to chime in this point, specifying dependencies here only require the existence of ducc0 (and matching version if needed) to be fulfilled. How that's fulfilled would be up to the user installing it. E.g. the user can install ducc0 following the recommended command in its documentation first and then install this package (which will not reinstall ducc0 as it is already satisfied.)

Alternative, after the user installed this package, they can run the recommended command to install ducc0 again (which will uninstall the first installation first and then compile it the 2nd time.)

**Comment by mayamkay** [comment]
Hi all,

I've been testing version 0.19.0 for the colab notebooks we're putting together and noticed that the `curvedsky.map2alm` function seems to still have some weird behaviour. @zatkins2 and I tested it a bit, and it seems that passing `method= 2d` gives alms that are consistent with the alms produced by version 0.17.3 for the same map, but that the default `method=cyl` results in alms that have a much larger amplitude (by a factor of about 7 for the patch I was using to test this).


Thanks for working on updating pixell and sorry to be adding onto the todo list!

**Comment by amaurea** [comment]
@mayamkay Do you have a test case we can use to reproduce the issue?

**Pull request merged**
