### PR TITLE
Libsharp2

### PR DESCRIPTION
**Pull request by AdriJD**
I have updated the version of libsharp, the spherical harmonic transform library, to the libsharp2 library. You can find the libsharp2 library here: https://gitlab.mpcdf.mpg.de/mtr/libsharp. The main difference between this version of libsharp and the older version is an increase in speed due to a faster algorithm for the computation of the associated legendre polynomials. I noticed that the speed increase is significant (about a 50 to 100% increase) so I figured it would be useful to make this available to all users of pixell. 

I have attached two benchmarks I performed comparing the new and old pixell SHT transforms to demonstrate the speed up. I show wall-time times the number of openmp threads for ntreads=1, 10 and 40 for a range of lmax values. Each point corresponds to the average of 5 (almI, almE, almB) -> (I, Q, U) transforms for the panel labeled alm2map and vice versa for the panel labeled map2alm. I'm using the Gauss-Legendre pixelization scheme. Two figures are shown, for the first I used the intel compiler (icc 19.0.1.144) and for the second I used gcc (gcc 9.3.1). In both cases the compilation flags were set to those recommended by the COMPILE file in the libsharp2 repo, they include -O3 and -ffast-math. The test was done on one of the 40 core 2.4 GHz Skylake nodes of the princeton tiger cluster.

ICC
timing

GCC
timing

From the figures it is clear that the new version of libsharp is about 1.5-2 times as fast, more or less independent of lmax, nthreads, or the compiler.

The changes I made were:

1. Changed the `scripts/install_libsharp` script to clone the libsharp2 repo from https://gitlab.mpcdf.mpg.de/mtr/libsharp if no install is found. The script will configure the libsharp2 build such that the include files and library will end up in `_deps/libsharp2/build`. So if people use the libsharp install in `_deps/libsharp` for other projects this new install will not overwrite that version of libsharp. Only a static libsharp library is produced, this matches how pixell currently installs libsharp1.  I think this is needed to have the automatic build work and lets users use `python setup.py install --user` without adding `_deps/libsharp2/build/lib` to their `LD_LIBRARY_PATH`.
2. Updated the `setup.py` script to point to the new include and library files.
3. Updated `cython/csharp.h` file to point to the new include files.
4. Updated `cython/csharp.pxd` to use the new definition of `sharp_execute`. This is needed because libsharp2 does not support the `ntrans` option. The libsharp2 repo states that there is no speed increase anymore when performing several transforms at the same time with the new algorithm so this functionality has been removed.
5. Updated `cython/sharp.pyx` to use the new definition of `sharp_execute`. In cases where alms/maps with shape=(ntrans, nspin, nalm/npix) with ntrans!=1 are provided the code now uses a for loop from 1 to ntrans to handle this case. I also fixed an unrelated bug that would show up when `alm2map_der1` would be called with alms with shape=(ntrans,2,npix) with ntrans!=1 that probably went unnoticed up to now.
6. I added two tests to `pixell/tests` that test the `alm2map`, `map2alm` and `alm2map_der1` wrappers from `cython/sharp.pyx`.
7. Updated the `README` file to refer to libsharp2.

So in the end, someone using the functions from `pixell/curvedsky` should not have to change anything to their own code to make use of these faster transforms.

### CODE REVIEW

**Comment by msyriac** [comment]
Oof, this will have a really positive impact on lots of applications! And thank you for the very comprehensive PR. I will test and get back.

**Comment by damonge** [comment]
This is great!

**Comment by thibautlouis** [comment]
Yep this is awesome, our life potentially became twice simpler

Le jeu. 4 févr. 2021 à 21:14, David Alonso <notifications@github.com> a
écrit :

**Comment by mreineck** [comment]
Hi, I just stumbled upon this by pure accident... good timing it seems :-)
It's great if you make the switch to `libsharp2` ... I'm actually thinking about placing a clear deprecation notice into the `libsharp` repository since it really shouldn't be used any more, at least for new projects.,,
I'm not completely sure how `pixell` uses the SHTs, but if you do not need direct MPI support from the `libsharp` functions, I might even have something better for you. There is now a small package at https://gitlab.mpcdf.mpg.de/mtr/ducc, which contains (among others) libsharp functionality, is completely portable C++17 and has no external dependencies (not even OpenMP, it works with standard C++ threads). It comes with a simple Python interface, and it should be possible to integrate it directly into `pixell` if you prefer that, eliminating one source of complication for users. The only drawback at the moment is that it does not use MPI (of course it can still be used in MPI-parallel codes, it just doesn't do any MPI-parallelization on its own.
So just in case you'd be interested in this sort of thing (maybe not right now, but as a future option), let me know!

**Comment by mhasself** [comment]
Very cool speed boost!  I won't formally approve this because I think Mat and Sigurd are in better position.  Two minor things I see in passing:
- some a += b were changed to a = a + b in the cython.
- in one instance, #includes were commented out... delete them.

**Comment by AdriJD** [comment]
@mreineck Thanks for that update! I'll definitely give this a look. We are not using libsharp's built-in MPI implementation so we could consider swapping our own python wrapper for the wrapper in this package. 

On libsharp's MPI implementation: as far as I understand from the libsharp paper it does more than simply distribute rings over MPI rank; it also distributes m-modes over ranks during some sections of the algorithm. Do you have a sense for how much we could gain by using the built-in MPI functions when running libsharp on several nodes in a hybrid MPI and openmp case? So for example, I sometimes run libsharp distributed over 4 nodes using MPI while using 40 openmp threads on each node for lmax=5000 or 10000. However, I simply scatter and gather the rings of the map myself so each node is using the non-MPI version of libsharp. I remember doing a small benchmark at some point that showed me that my method was roughly as fast as using the built-in libsharp MPI method. I blamed the extra MPI communication that's needed for the m-mode distribution for that result, but I admit I didn't really test this properly. Would you expect that the built-in MPI version should outperform the other method for a case like this?

@mhasself Thanks for spotting those. I'll remove the commented-out things. On the a+= b thing: I didn't understand why this issue popped up, but I wasn't able to compile (I think with ICC) the cython code without changing it to a = a + b. I was confused about this, because I did not make any changes to this part of the code.

This is the error I got for `alm[c1,lm] += lmat[c1,c2,l] * v[c2]`

```
cython/sharp.c(11367): error: expression must have arithmetic or pointer type
            *__Pyx_BufPtrStrided2d(__pyx_t_double_complex *, __pyx_pybuffernd_alm.rcbuffer->pybuffer.buf, __pyx_t_22, __pyx_pybuffernd_alm.diminfo[0].strides, __pyx_t_21, __pyx_pybuffernd_alm.diminfo[1].strides) += __pyx_t_double_complex_from_parts(__Pyx_CREAL(__pyx_t_28), __Pyx_CIMAG(__pyx_t_28));
            ^

compilation aborted for cython/sharp.c (code 2)
error: Command "icc -m64 -fPIC -fp-model strict -O3 -fomit-frame-pointer -qopenmp -I/home/adriaand/.pyenv/versions/enki/lib/python3.8/site-packages/numpy/core/include -I/home/adriaand/.pyenv/versions/enki/lib/python3.8/site-packages/numpy/core/include -I_deps/libsharp2/build/include -I/home/adriaand/.pyenv/versions/enki/include -I/home/adriaand/.pyenv/versions/3.8.3/include/python3.8 -c cython/sharp.c -o build/temp.linux-x86_64-3.8/cython/sharp.o -MMD -MF build/temp.linux-x86_64-3.8/cython/sharp.o.d -std=c99 -fopenmp -Wno-strict-aliasing -g -Ofast -fPIC" failed with exit status 2
```

This is the relevant part in `cython/sharp.c`

```          /* "sharp.pyx":380                                                                                           
 *                                      for c2 in range(ncomp):                                                        
 *                                              #alm[c1,lm] = alm[c1,lm] + lmat[c1,c2,l] * v[c2]                       
 *                                              alm[c1,lm] += lmat[c1,c2,l] * v[c2]             # <<<<<<<<<<<<<<       
 *                      # If lmat is too short, interpret missing values as zero                                       
 *                      for l in range(lcap, self.lmax+1):                                                             
 */
          __pyx_t_17 = __pyx_v_c1;
          __pyx_t_21 = __pyx_v_c2;
          __pyx_t_22 = __pyx_v_l;
          __pyx_t_26 = __pyx_v_c2;
          __pyx_t_27 = (*__Pyx_BufPtrStrided1d(__pyx_t_double_complex *, __pyx_pybuffernd_v.rcbuffer->pybuffer.buf, __\
pyx_t_26, __pyx_pybuffernd_v.diminfo[0].strides));
          __pyx_t_28 = __Pyx_c_prod_npy_float64(__pyx_t_npy_float64_complex_from_parts((*__Pyx_BufPtrStrided3d(__pyx_t\
_5numpy_float64_t *, __pyx_pybuffernd_lmat.rcbuffer->pybuffer.buf, __pyx_t_17, __pyx_pybuffernd_lmat.diminfo[0].stride\
s, __pyx_t_21, __pyx_pybuffernd_lmat.diminfo[1].strides, __pyx_t_22, __pyx_pybuffernd_lmat.diminfo[2].strides)), 0), _\
_pyx_t_npy_float64_complex_from_parts(__Pyx_CREAL(__pyx_t_27), __Pyx_CIMAG(__pyx_t_27)));
          __pyx_t_22 = __pyx_v_c1;
          __pyx_t_21 = __pyx_v_lm;
          *__Pyx_BufPtrStrided2d(__pyx_t_double_complex *, __pyx_pybuffernd_alm.rcbuffer->pybuffer.buf, __pyx_t_22, __\
pyx_pybuffernd_alm.diminfo[0].strides, __pyx_t_21, __pyx_pybuffernd_alm.diminfo[1].strides) += __pyx_t_double_complex_\
from_parts(__Pyx_CREAL(__pyx_t_28), __Pyx_CIMAG(__pyx_t_28));
```
I suspect that this has to do with some sort of type conversion between complex and real arrays that is not done correctly (although I don't see why it should not work). In any case, I figured that the `alm[c1,lm] = alm[c1,lm] + lmat[c1,c2,l] * v[c2]` version somehow does the implicit type conversion correctly so I used that.

**Comment by AdriJD** [comment]
I'm going to run the benchmarks for CAR and healpix pixelization too. Mat was interested in seeing those. I'll post them here.

**Comment by mreineck** [comment]
> @mreineck Thanks for that update! I'll definitely give this a look. We are not using libsharp's built-in MPI implementation so we could consider swapping our own python wrapper for the wrapper in this package.

Sounds good! Please let me know if there are any questions.

> On libsharp's MPI implementation: as far as I understand from the libsharp paper it does more than simply distribute rings over MPI rank; it also distributes m-modes over ranks during some sections of the algorithm.

Correct, but it does that mostly for memory balancing. If you don't do that, you end up with a full a_lm set on every node, which is sub-optimal but may not be a problem at all, depending on your band limit.

> Do you have a sense for how much we could gain by using the built-in MPI functions when running libsharp on several nodes in a hybrid MPI and openmp case? So for example, I sometimes run libsharp distributed over 4 nodes using MPI while using 40 openmp threads on each node for lmax=5000 or 10000. However, I simply scatter and gather the rings of the map myself so each node is using the non-MPI version of libsharp.

That is fine as long as you distribute the rings in a way that lead to a balanced CPU workload, and if you keep pairs of rings that are symmetric with respect to the equator on the same node. My suggestion would be to distribute rings round-robin among nodes, going from North pole to equator and always adding the corresponding ring on the southern hemisphere to the same node as its partner. Not keeping the ring pairs together will drop performance to 50%.

> I remember doing a small benchmark at some point that showed me that my method was roughly as fast as using the built-in libsharp MPI method. I blamed the extra MPI communication that's needed for the m-mode distribution for that result, but I admit I didn't really test this properly. Would you expect that the built-in MPI version should outperform the other method for a case like this?

No. Libsharp does not do any MPI load balancing on its own; you have to already feed it the problem in a balanced fashion. The only thing it does is the "transpose" operation that switches between the "rings distributed over nodes" and "m values distributed over nodes" states.

**Comment by mreineck** [comment]
Also, just as a word of caution: I would use MPI SHTs only for _very, very_ large maps ... the problems with load balancing can be quite severe. If there is a choice between doing one SHT on multipe nodes and doing several different SHTs in parallel, always do the latter!

**Comment by AdriJD** [comment]
@mreineck Okay, that makes sense! Thank you for such an elaborate answer! 

@msyriac I ran three more benchmarks. I only averaged 2 runs for each point so there is a bit more scatter. 

1. A healpix grid (with nside >= lmax / 3). Directly using the functions from `cython/sharp.pyx`
2. A Clenshaw Curtis grid with nrings = 2 * lmax. Directly using the functions from `cython/sharp.pyx`
3. A full sky CAR enmap with nrings = 2 * lmax. So with the same number of pixels as case 2. This time I'm directly using `curvedsky.alm2map(alm, omap, ainfo=ainfo, spin=spin, direct=True)` and `curvedsky.map2alm(omap, alm, ainfo=ainfo, lmax=lmax, spin=spin, direct=True)`, so I'm letting pixell create all the map_info metadata needed for sharp. This should reduce to case 2, but it tests whether there is some overhead in calling from `pixell.curvedsky` instead of `pixell.sharp`.

I see roughly the same speed increase in going from libsharp1 to libsharp2 as before. Case 2 and 3 are very similar for alm2map, but case 2 is faster for map2alm. That's something we could track down, but it's unrelated to this PR because I see the same for libsharp1 and libsharp2.

1. Healpix
timing
2. Clenshaw Curtis
timing
3. CAR enmap
timing

**Comment by mreineck** [comment]
I know this is getting really off-topic, but I can't resist...
When you are doing SHTs on large Clenshaw-Curtis grids (or anything equidistant in theta really), there is a neat trick that can give up to a factor of 2 in `alm2map` perfrmance: instead of using the full `2lmax+1` rings, it is actually sufficient to do an SHT on `lmax+2` equidistant rings with (for example) the first and last rings lying on the poles. It's true that there is no simple quadrature rule to go from such a grid back to the original a_lm, but nevertheless it holds the full information that was contained in the original a_lm.
Assuming you also have an even number of pixels in phi direction, you can "FFT-shift" the values along every meridian to the latitudes you need and, for example, compute the values on rings lying exactly between the ones you computed with `alm2map`.
The additional double FFT along meridians required for this is not cheap, but if your map is sufficiently large it will easily beat the full Clenshaw-Curtis SHT with `2lmax+1` rings.
Now it would be great is there was an analogous trick for
 the `map2alm` direction, but I haven't found one so far ...

@AdriJD, if you have a look at the `ducc` package, please also check out the demo files `python/demos/totalconvolve_*.py`! This functionality might be handy for doing all the numerical heavy lifting in the core of `beamconv`.

**Review by msyriac — APPROVED** [review]
Tested through the lensing reconstruction pipeline where I see ~40% gains and no issues, so I'm approving this! And thank you for the detailed CAR and healpix tests @AdriJD !

**Comment by damonge** [comment]
Out of curiosity: I implemented this in namaster but I'm not seeing a noticeable speed-up. I'm using gcc and doing this for healpix (nside=512 in the test). Any ideas?

**Comment by msyriac** [comment]
@damonge how about for larger nside (2048) and low OpenMP threads (~10) ?  I initially didn't notice any difference in the lensing pipeline, but that was because for the first test case I ran with threads=40, the SHTs were so fast that the bottleneck was non-threaded numpy arithmetic (transforming alms into the form needed for libsharp). With nthreads=10 (which is what we would end up using), the SHTs were more important and I saw the 40% improvement with libsharp2 I mentioned.

**Comment by AdriJD** [comment]
Hi @damonge, as Mat said, I would double check whether the SHT is really the dominant part of you test. I still saw improvements for the lmax=1000 and lmax=2000 case. Otherwise, you can check if you actually compiled with -ffast-math etc. See https://gitlab.mpcdf.mpg.de/mtr/libsharp/-/blob/master/COMPILE. Or were you perhaps comparing to `healpy`? (because that's already using libsharp2).

**Comment by AdriJD** [comment]
@mreineck That's a really neat trick! I see why that would work. We do use a lot of maps that are equidistant in theta, so this would be a useful addition to pixell's `alm2map` operation.

Jon Gudmundsson (@jegudmunds) and I had indeed noticed your totalconvolve package! I agree it would be a nice thing to implement in `beamconv`!

**Comment by msyriac** [comment]
Will merge this today (spoke with @amaurea )

**Pull request merged**
