### PR TITLE
enmap: fix area and fullsky_geometry functions.

### PR DESCRIPTION
**Pull request by mhasself**
Addresses #70 .

The area() function now computes area precisely and quickly in a broad
class of geometries.  The fullsky_geometry function is more careful
with the RA axis native coordinate system branch cut; now all pixels
in the grid (that are not at the poles) have valid coordinates (across
their entire areas).

### CODE REVIEW

**Comment by msyriac** [comment]
Thanks, will have a look. Are the test failures expected? If yes, I can regenerate them.

**Comment by mhasself** [comment]
Oh, sorry I didn't check the original test suite...  I just fixed the (hilarious) area check test... the other two will require you to regenerate the reference cases.

**Comment by msyriac** [comment]
The hilarious area test tells you how long I've known of this problem and ignored it :/

Sigurd points out that your area function doesn't address an underlying inaccuracy in enmap.extent (which is also used to get Fourier wavenumbers). More soon.

**Comment by msyriac** [comment]
Closing since this was merged with #77 .

**Pull request closed without merging**
