### PR TITLE
Make it so that users can run the tests when not in "develop" mode.

### PR DESCRIPTION
**Pull request by mhasself**
Addresses #19.

The crux here is to group tests into a class that inherits from unittest.TestCase.  That's no burden since the tests are all segmented into tests/ already anyway.

I've broken some indentation rules, but that can be fixed in a separate white-space-only commit.

### CODE REVIEW

**Comment by msyriac** [comment]
Ok, I've tried it out. As usual "py.test" works when either "python setup.py build_ext -i" or "python setup.py develop --user" is used. But neither "py.test" nor "python setup.py test" works after installing the package using "python setup.py install --user". Here is the full output for both tries:
https://pastebin.com/QBAYmpGp

**Comment by mhasself** [comment]
As I understand it, the py.test problem is fundamental and thus not ours to solve.  The "setup.py test" path can probably be diverted to work, though.  But in any case the usage I intended is explained in the commit message (I'm sure you know a better place for that info to live...).  The crux is that you can now do:

```
  cd tests
  python test_pixell.py
```

This invocation will run the tests, using the same unittest framework that py.test uses, but taking pixell from the usual import path instead of from ../pixell.

**Comment by msyriac** [comment]
`python test_pixell.py` however doesn't do anything because that script only has function definitions and no function calls. Only a "test framework" like "python setup.py test" or "py.test" can discover and call those functions and check which ones passed.

**Comment by msyriac** [comment]
Never mind, I wasn't on your branch!

**Comment by msyriac** [comment]
With the changes I just pushed,
"python setup.py test"
works after
"python setup.py install --user"

If you are ok with this, I will update the docs and merge this PR.

**Comment by mhasself** [comment]
Great.  Seems fine.  Thanks.

**Pull request merged**
