### PR TITLE
Use versioneer to manage code version.

### PR DESCRIPTION
**Pull request by mhasself**
https://github.com/warner/python-versioneer

Instead of hard-coding and manually bumping versions, they can be auto-generated using well-structure git tags (such as the ones already used to tag releases in pixell).  The nice thing is it automatically marks the version with additional info in the case that you're a few commits ahead of the official version.  (e.g. 0.4.0+3.gefbdd6f to indicate 3 commits ahead of version 0.4.0).

### CODE REVIEW

**Comment by mhasself** [comment]
Ignore this for now... it may not be the versioning panacea I had hoped.

**Comment by mhasself** [comment]
Never mind.  It _is_ the panacea I had hoped.  Please resume your consideration of this pull_request!

**Comment by msyriac** [comment]
Thanks Matthew, I'll have a look. I'm curious about your sine wave of opinions though. And should one be worried that the versioneer package hasn't been updated in more than a year?

**Comment by mhasself** [comment]
Have I created such a prior expectation of oscillation that you interpret the recent delta function as a sine wave?? :)  I had vetted this thing fairly thoroughly, actually, but there was one situation I had not thought of: because versioneer needs the github commit+tag information to generate a version code, I suddenly realized that it might fail to compute a valid tag if one was building from a release tarball instead of from a git repo.  (I knew it could already handle the case of building and installing code through setup.py, if done from a git repo.)  But it turns out that versioneer has the export case covered as well, through the use of an export-subst hook (which amounts to: when "exporting" the source from git, do some textual substitutions on _version.py to replace some place-holder symbols with some info from git).

I've added a description of versioneer and a recommendation to use it into the so_dev_guide; take a look there for a bit more background.

**Comment by msyriac** [comment]
Ok, I like this. The only difference with the way things are currently being done is that I have to "think" about what the next version is called and can't abstract it out to "bumpversion patch", "bumpversion  minor", or "bumpversion major". I have to check what the last tag was and then increment it accordingly. Not a big deal, but just making sure I'm not missing what the suggested procedure is?

Also, looking at the .travis.yml file, it seems like the "auto deploy to PyPI on new version" thing we currently have will not be affected. Right? That seems to be just tied to tagging, and not bumpversion itself.

**Comment by mhasself** [comment]
Actually I think you can use bumpversion and versioneer together.  Was not aware of bumpversion before.  Currently your bumpversion is configured to do (at least) these things:

- picks a new version number
- creates a git tag of the form vX.y.z
- modifies ``setup.py`` and ``pixell/__init__.py``
- commits those changes.
- assigns the git tag to HEAD

You just have to turn off steps 3 and 4.  To do that... clearly you'd comment out the bumpversion:file blocks in setup.cfg.  And also set commit = False, I think.  In your current approach, do you have to "git push --tags"?  You would still have to do that.

**Comment by mhasself** [comment]
@msyriac  Are you now satisfied that versioneer works ok with bumpversion and PyPI?  If so, this is ready for squash+merge.

**Comment by msyriac** [comment]
Sorry for the delay in approving this. @mhasself could we decide on some text to go into the docs on the proper procedure for tagging / bumping versions ? Does this already exist somewhere?

**Comment by mhasself** [comment]
I've updated the text in CONTRIBUTING.rst; see https://github.com/simonsobs/pixell/pull/31/commits/eea7f230a7af8c985586aab999476198f2758b6d.  It looks like one does actually need a separate release commit (bumpversion:commit=True) because bumpversion needs to record the version number in setup.cfg.  That's fine.  I am not sure if the contributing.rst text is perfectly accurate now, but otherwise I think we could rebase+squash+merge this and then try to create v0.5.2 and see if it works. (I don't know of any more testing that can be done while not on master branch.)

**Comment by msyriac** [comment]
Seems to work as expected when following instructions in contributions.md. Thanks Matthew, and sorry this took so long! I still have to manually enter the version number in HISTORY.rst when deploying -- but this is just bumpversion not being sophisticated enough.

**Pull request merged**
