### PR TITLE
added eb2spin and spin2eb

### PR DESCRIPTION
**Pull request by xzackli**
This adds a pair of utility functions for going between +/- and E/B polarization spherical harmonic coefficients. Sigurd wrote the batch stuff.

### CODE REVIEW

**Comment by msyriac** [comment]
Sorry I missed this @xzackli, looks useful. Can you update this with current master and resolve any conflicts before we merge?

**Comment by msyriac** [comment]
Could you also mention in the doc-string that the transformation can be done in-place if the same arrays are passed for input and output?

**Comment by mreineck** [comment]
Sorry, I just stumbled across this by accident...

Just one question: in the (admittedly unlikely, but possible) case that any of the involved a_lm arrays is 1) very large and 2) noncontiguous, won't the repeated `reshape(-1)` calls lead to tremendous amounts of copying and unnecessary memory consumption?

**Comment by xzackli** [comment]
Yep. If `reshape` doesn't return an array view, then these routines will be truly awful. Sadly, `reshape`-based routines exist elsewhere in pixell. Maybe this should all be cython so we could just write for loops.

**Comment by amaurea** [comment]
@mreineck I have always thought of .reshape(-1) as free, but now that I think of it, the striding for a 1d array is not general enough to support all types of multidimensional striding. So this would have to lead to copies. One could move the reshape outside the loop, but if the layout causes copies, then the loop doesn't make sense in the first place. Is there a good way to loop over bunches of elements for arrays with general shapes and general layouts?

**Comment by mreineck** [comment]
> I have always thought of .reshape(-1) as free, but now that I think of it, the striding for a 1d array is not general enough to support all types of multidimensional striding. So this would have to lead to copies.

Yes, and if the `reshape(-1)` of the _output_ array requires a copy, the "real" output array stays completely unchanged. In other words, is some cases this is not only a performance, but also a correctness problem. Granted, this is not an everyday occurrence, but that makes debugging even more difficult in the rare cases where it happens.

I don't know about a simple way to split this kind of operation into batches, but I'm not sure that there is much to gain in this concrete situation by using batches. Is the goal to avoid large temporary arrays? If so, then perhaps one could do something like this: instead of

`alm_plus = -E - 1j * B`

one might write something along the lines of

```
alm_plus[()] = B
alm_plus *=-1j
alm_plus -= E
```

Not beautiful at all, but it should do the trick.

**Pull request closed without merging**
