### PR TITLE
Nemo

### PR DESCRIPTION
**Pull request by mattyowl**
Hi - don't know if you want the enlib pointsrcs module in pixell, but I've added it here (tweaked the code for reading catalogs a little). I'm using this for adding tests for sanity checking nemo that are easy to run.

### CODE REVIEW

**Comment by msyriac** [comment]
I feel this is great to have in pixell, but Sigurd @amaurea needs to commit to maintaining it here rather than in enlib.

**Comment by mattyowl** [comment]
Alternatively, I can stick it into nemo and credit Sigurd for it - I 
don't mind either way. I don't want to have dependencies on both enlib 
and pixell though.

**Comment by mattyowl** [comment]
This is no longer needed

**Comment by msyriac** [comment]
Hi @mattyowl , what did you decide to go with (a) put this stuff in nemo (b) import enlib or (c) not use it at all? @amaurea  it would be great if pointsrcs could be moved from enlib to pixell.

**Comment by mattyowl** [comment]
I'm not using it at all - I was only using ptsrcs for doing tests 
(recovered point source amplitudes), but I wrote something in nemo to do 
this instead (I want to do both clusters and sources anyway), so nemo 
only needs the current 'master'/latest release of pixell.

**Comment by msyriac** [comment]
FYI @mattyowl pointsrcs.py is now in pixell (h/t Sigurd)

**Pull request closed without merging**
