### PR TITLE
added routine for lensing predefined alms (allows to do lensing for f…

### PR DESCRIPTION
**Pull request by ajvanengelen**
…ields that are not gaussian random fields.

I wrote a new routine that takes all the lines from the existing lensing.rand_map, but allows one to pass in externally-determined maps for both phi and for the CMB.  (I need this for doing the lensing with the more realistic non-Gaussian matter fields coming from nonlinear structure, e.g. the Websky simulations that we are using for SO.)  This type of functionality also allows for lensing of CMB maps with primordial non-Gaussianity.

### CODE REVIEW

**Comment by msyriac** [comment]
This looks great to me (haven't actually tested it myself though). The name of the function however conflicts with an existing flat-sky routine. Could you fix it?

**Comment by msyriac** [comment]
One other issue is code duplication. Do you think it's possible for rand_map to call your new lens_map, instead of duplicating code (which means two places to track future bug fixes / changes).

**Comment by ajvanengelen** [comment]
Whoops!  I wonder why it worked.  Suggestions for the name?

**Comment by ajvanengelen** [comment]
I almost did that, thought about that, but didn't want to mess with the 
existing code too much.  Sigurd, do you have thoughts / suggestions on 
how to proceed?

**Comment by msyriac** [comment]
I think it worked because Python supports reclaiming functions in the namespace, just like with variables. So the later definition of lens_map was what was used.

Some suggestions:
lens_map_curved
get_lensed_map

Maybe @amaurea has other suggestions.

**Comment by ajvanengelen** [comment]
OK, "lens_map_curved" it is.  regarding code duplication, @amaurea, please let me know if you would like me to take a shot at reworking lensing.rand_map to have it call the new lensing.lens_map_curved.

**Comment by msyriac** [comment]
I've made lensing.rand_map call lensing.lens_map_curved. I've added continuous integration tests and made sure these changes haven't changed outputs of rand_map. I've also made ainfo optional.

**Comment by msyriac** [comment]
Note: make lens_map_curved accept unlensed map, not cmb_alm

**Comment by msyriac** [comment]
Oh wow, that was painful. Long story short, I tried to add some tests that make sure the outputs of lensing are consistent, but numerical noise was getting amplified somewhere to the point that maps made on different computers only agreed at the 0.7% level (much worse than double precision). Sigurd and I tried to track this down today and think it's happening in the trigonometric operations in lensing.offset_grad_helper. For now, the tests have been reduced in stringency, and I think this is ready to merge (but after squashing commits).

**Comment by msyriac** [comment]
Finally fixed that lensing discrepancy. It was because I was using nonsensically large lensing powers, thus pushing Sigurd's routine's into (nonsensically) ultra strong lensing. I'm merging this soon.

**Pull request merged**
